sonar.projectKey=Kane2710_smart-budget-basket-api
sonar.organization=kane2710
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**,.git/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8